version: '3'
services:
  bind:
    image: ubuntu/bind9:latest
    container_name: bind-dns
    environment:
      - BIND9_USER=root
      - TZ=America/New_York
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
    volumes:
      - ./bind-config:/etc/bind
      - ./bind-cache:/var/cache/bind
      - ./bind-records:/var/lib/bind
      - ./bind-tsigkey:/var/tsigkey
    networks:
      - appnetwork

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx-proxy-conf:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - appnetwork

  webapp1:
    image: nginx:latest
    container_name: webapp1
    volumes:
      - ./webapp1:/usr/share/nginx/html
    networks:
      appnetwork:
        ipv4_address: 172.23.0.10


  webapp2:
    image: nginx:latest
    container_name: webapp2
    volumes:
      - ./webapp2:/usr/share/nginx/html
    networks:
      appnetwork:
        ipv4_address: 172.23.0.11

networks:
  appnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24

# reference to common command for IP address discovery
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container>

# very last step is to add the resolver on the MacOS host under /etc/resolver, one file per FQDN
# sudo echo 'webapp1.local 127.0.0.1' > /etc/resolver/webapp1.local
# etc.. 
# restart local mac dns resolver with 'sudo killall -HUP mDNSResponder; sudo dscacheutil -flushcache;'
